name: Unit test coverage

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Unit test coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: pcov

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

      - name: Send coverage to Scrutinizer
        run: vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
